apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k8s-example-project/devops.git
    path: k8s/project/postgres
    targetRevision: add-k8s-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: notes
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
