# Used for demonstration purposes only. 
# Never store secrets in plain text or base64 encoded in production. 
# Use a secure way like sealed secrets or HashiCorp Vault to store secrets instead.
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: notes
  labels:
    app: postgres
stringData:
  POSTGRES_DB: notesdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
